title: Ivan Hurtado
description: Visual & Motion Designer — pixels with purpose.
url: "https://ivanhurba.github.io"
baseurl: ""

markdown: kramdown
permalink: pretty

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

author:
  name: Ivan Hurtado.
  location: Slovakia
  linkedin: https://www.linkedin.com/in/ivanhurba/
